-- kilo memory system schema（兼容指针）
-- ============================================================
-- 实际 DDL 已迁移到 .kilo/memory/schema/init.sql（v2.2 模块边界）
-- 本文件保留作为向后兼容入口（仅占位），新代码请直接引用 schema/init.sql
-- ============================================================
--
-- 模块架构: .kilo/memory/
--   README.md                ← 公共 API 文档
--   AGENTS.md                ← 模块对 agent 的指令入口
--   schema/init.sql          ← DDL 唯一源（5 表 + 索引 + 视图）
--   policy/*.md              ← 业务规则（7 个文件）
--   contracts/health_check.sql ← 健康度 SQL
--
-- ⚠️ 本文件不含 DDL；执行本文件等于 0 张表。
-- 推荐新调用：
--   sqlite3 "${HOME}/.config/kilo-data/memory.db" < .kilo/memory/schema/init.sql
-- 或通过 sqlite MCP 读 schema/init.sql 执行

-- 本文件本身不再包含 DDL（避免双源漂移）；DDL 全部在 schema/init.sql